url: https://y7kim.github.io
baseurl: '/tostado-y-colado/'

# Site settings
title: Tostado Y Colado
email: info@tostado-y-colado.com
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
api_key: ZmM5ZmM3NzYtYTJlYS00NTk1LTlmMWMtNzg3YjliNDkzZmQ3NjM2MjkyNjY0MTMxMzgxMDIz


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url: https://www.facebook.com/
  - title: instagram
    url: http://instagram.com/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

collections:
    - products
